### ISSUE TITLE
lombok, @Getter, тернарные операторы if, gitignore

### ISSUE THREAD

**Issue by Statuxia** [simply-kel/sMOTD#1]
Добавление lombok
Замена написанных вручную методов на @Getter
Замена if-else ужаса на тернарный оператор if
Добавление gitignore

https://drive.google.com/file/d/1X6MzGLzg8yYqC6YF7Om5K7D-3a3lPYwp/view?usp=sharing

**Comment by kel-cu** [comment]
Обновлено [commit](https://github.com/simply-kel/sMOTD/commit/1cfeef5273a9d0832327b58a353f26768b65059b)
